version: '2'
services:
  master:
    build: .
    volumes:
      - .:/usr/src/app
    command: python start.py
    env_file: .env
    depends_on:
      - rethinkdb
      - rabbitmq
    links:
      - rethinkdb
      - rabbitmq

  worker:
    build: .
    volumes:
      - .:/usr/src/app
      - ./.data:/home/admin/data
    command: celery -A worker worker --loglevel=info --pool=solo
    env_file: .env

    depends_on:
      - rethinkdb
      - rabbitmq
    links:
      - rethinkdb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.6

  rethinkdb:
    image: rethinkdb:2.3
    volumes:
      - ./.data:/data
    ports:
      - 8080:8080